// PLUGIN FUNCTIONS
typedef CHAR* (*XINFO)(VOID*, VOID*, VOID*, VOID*, VOID*, DWORD*, DWORD*);
typedef BOOL (*XSTART)(VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*);
typedef INT (*XMAIN)(VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*, VOID*);
