// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef MailReact_h
#define MailReact_h
#include <FL/Fl.H>
#include "TextEdit.H"
#include <FL/Fl_Output.H>
extern int start_sending();
extern TextBuffer *b;
extern TextBuffer *b2;
extern TextEdit *textedit;
extern TextEdit *Mail_text;
extern int abortit;
bufModifyCallbackProc bufModifiedCB(void *arg);
void save_data();
void log_text(Fl_Output *output,char *text);
#include <FL/Fl_Window.H>
extern Fl_Window *mailwin;
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *SMTPval;
extern Fl_Input *port;
extern Fl_Input *sender;
extern Fl_Input *subject;
extern Fl_Input *delay;
extern Fl_Input *mailsconnect;
extern Fl_Group *Receivers;
#include <FL/Fl_Scrollbar.H>
extern Fl_Scrollbar *h;
extern Fl_Scrollbar *v;
#include <FL/Fl_Box.H>
extern Fl_Group *Text;
extern Fl_Scrollbar *Text_v;
extern Fl_Scrollbar *Text_h;
#include <FL/Fl_Output.H>
extern Fl_Output *syslog;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *progress;
#include <FL/Fl_Button.H>
extern Fl_Button *Send;
extern Fl_Button *Abort;
extern Fl_Button *ExitButton;
extern Fl_Button *ClearLog;
extern Fl_Button *about;
Fl_Window* make_window();
extern Fl_Window *aboutwin;
extern Fl_Output *website;
Fl_Window* about_window();
#endif
