#ifndef __rat_types_h
#define	__rat_types_h

#define PACK_MIN					1000
#define	PACK_TYPE_SYNCHRO			1000
#define PACK_TYPE_DATA				1001
#define PACK_TYPE_CMD_REBOOT		1002
#define PACK_TYPE_CMD_RUN			1003
#define PACK_TYPE_CMD_PROCLIST		1004
#define PACK_TYPE_CMD_TERMINATE		1005
#define PACK_TYPE_CMD_REGLIST		1006
#define PACK_TYPE_CMD_REGDELETE		1007
#define PACK_TYPE_CMD_REGADD		1008
#define PACK_TYPE_CMD_SHOWSHARED	1009
#define PACK_TYPE_CMD_SHOWCONN		1010
#define PACK_TYPE_CMD_DISCONNDRV	1011
#define PACK_TYPE_CMD_CONNDRIVE		1012
#define PACK_TYPE_CMD_FIND			1013
#define PACK_TYPE_CMD_DELETE		1014
#define PACK_TYPE_CMD_COPY			1015
#define PACK_TYPE_CMD_MOVE			1016
#define PACK_TYPE_CMD_DISKLIST		1017
#define PACK_TYPE_CMD_SYSINFO		1018

#define	PACK_MAX					1018
#define	SYNCHRO_SIGN			0x20544152
#define	RATMSG_SOCKET			WM_USER+1

typedef struct
{
	DWORD	PacketType;
	DWORD	DataSize;
} PACKETHEAD;

#endif