#pragma once
#include "winioctl.h"
//IOCTRL

#define ZION_SERVER_IOCMD      0x00003A1B


/*
    CS : Client To Server


*/


#define IOCTL_ZION_CS_INIT     \
    (ULONG)CTL_CODE(FILE_DEVICE_ZION, 0x01, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_ZION_CS_LOGIN     \
    (ULONG)CTL_CODE(FILE_DEVICE_ZION, 0x02, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_ZION_CS_PKT_CMD     \
    (ULONG)CTL_CODE(FILE_DEVICE_ZION, 0x03, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_ZION_CS_LOGOFF       \
    (ULONG)CTL_CODE(FILE_DEVICE_ZION, 0x04, METHOD_BUFFERED, FILE_WRITE_ACCESS)
